[package]
name = "find-chain"
version = "0.1.0"
authors = ["nanlei.roy <nanlei.roy@bytedance.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"
rand = "*"
